id: P716B3BB0
initial_creation_type: input
source_metadata:
  title: Ngöndro Commentary by Chökyi Drakpa
  language: fr
  description: 'The commentary on the preliminary practices of Longchen Nyingtik by
    Chökyi Drakpa (chos kyi grags pa):'
  volume:
    eca809d8580e412bae5f9ee77a72ea14:
      title: 'A Torch for the Path to Omniscience: A Word by Word Commentary to the
        Longchen Nyingtik Ngöndro'
      parent: null
created_at: '2022-02-28T22:48:13.460948'
last_modified_at: '2022-02-28T22:48:13.460954'
